### ISSUE TITLE
After starting kibana unable to connect to Elasticsearch

### ISSUE THREAD

**Issue by 7olstoy** [vania-pooh/elk-config#2]
After docker-compose up -d in kibana dashboard you can see

Status: Red
Status Breakdown

plugin:kibana@6.2.1 | Ready
plugin:elasticsearch@6.2.1 | Unable to connect to Elasticsearch at http://elasticsearch:9200.
plugin:timelion@6.2.1 | Ready
plugin:console@6.2.1 | Ready
plugin:metrics@6.2.1 | Ready

**Comment by vania-pooh** [comment]
@A-styler you should have on the same machine a running container named `elasticsearch`. This is how Docker networks work. Execute `docker ps -a` and check whether Elasticsearch is running.

**Comment by 7olstoy** [comment]
After creating everything looks good 

```
Creating elk_elasticsearch_1 ... done
Creating elk_logstash_1      ... done
Creating elk_kibana_1        ... done
```
```
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                  PORTS                              NAMES
0c85b4b36e0b        docker.elastic.co/kibana/kibana-oss:6.2.1             "/bin/bash /usr/loca…"   5 seconds ago      Up 3 seconds            0.0.0.0:5601->5601/tcp             elk_kibana_1
c8de16a225ee        docker.elastic.co/logstash/logstash-oss:6.2.1         "/usr/local/bin/dock…"   5 seconds ago      Up 3 seconds   0.0.0.0:5044->5044/tcp, 9600/tcp   elk_logstash_1
45a165d00365        docker.elastic.co/elasticsearch/elasticsearch:6.2.1   "/usr/local/bin/dock…"   5 seconds ago      Up 3 seconds    0.0.0.0:9200->9200/tcp, 9300/tcp   elk_elasticsearch_1
```
But after it I saw that latest containers was restarted and logs show me low memory error.
So please add to technical recommendations >4Gb of free RAM
